// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package models

import (
	"database/sql"
)

type Catalog struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type CatalogsItem struct {
	ID         int64        `json:"id"`
	Identifier int64        `json:"identifier"`
	Label      string       `json:"label"`
	CatalogID  int64        `json:"catalog_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type Response struct {
	ID                           int64        `json:"id"`
	Identifier                   int64        `json:"identifier"`
	Gender                       int64        `json:"gender"`
	Age                          int64        `json:"age"`
	AgeUnit                      int64        `json:"age_unit"`
	Birthdate                    string       `json:"birthdate"`
	Deathdate                    string       `json:"deathdate"`
	Variable1                    string       `json:"variable1"`
	Variable2                    string       `json:"variable2"`
	A                            string       `json:"a"`
	TimeA                        int64        `json:"time_a"`
	TimeUnitA                    int64        `json:"time_unit_a"`
	B                            string       `json:"b"`
	TimeB                        int64        `json:"time_b"`
	TimeUnitB                    int64        `json:"time_unit_b"`
	C                            string       `json:"c"`
	TimeC                        int64        `json:"time_c"`
	TimeUnitC                    int64        `json:"time_unit_c"`
	D                            string       `json:"d"`
	TimeD                        int64        `json:"time_d"`
	TimeUnitD                    int64        `json:"time_unit_d"`
	Part2                        string       `json:"part_2"`
	TimePart2                    int64        `json:"time_part_2"`
	TimeUnitPart2                int64        `json:"time_unit_part_2"`
	Surgery                      int64        `json:"surgery"`
	SurgeryDate                  string       `json:"surgery_date"`
	Autopsy                      int64        `json:"autopsy"`
	UsedFoundings                int64        `json:"used_foundings"`
	MannerOfDeath                int64        `json:"manner_of_death"`
	PlaceOfDeath                 int64        `json:"place_of_death"`
	MultiplePregnancy            int64        `json:"multiple_pregnancy"`
	HoursAlive                   int64        `json:"hours_alive"`
	WeightInGrams                int64        `json:"weight_in_grams"`
	FullWeeksOfPregnancy         int64        `json:"full_weeks_of_pregnancy"`
	MotherAgeInYears             int64        `json:"mother_age_in_years"`
	WomanPregnancyCondition      int64        `json:"woman_pregnancy_condition"`
	PregnancyContributionToDeath int64        `json:"pregnancy_contribution_to_death"`
	CreatedAt                    sql.NullTime `json:"created_at"`
	UpdatedAt                    sql.NullTime `json:"updated_at"`
}
